import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:mockito/mockito.dart';
import 'package:finder/features/auth/presentation/providers/auth_provider.dart';

// Assume mocks.mocks.dart is generated by build_runner
// import '../mocks.mocks.dart';

void main() {
  test('AuthNotifier login success sets state to true', () async {
    // Setup Mocks
    // final mockDio = MockDio();
    // when(mockDio.post(any, data: anyNamed('data'))).thenAnswer(
    //   (_) async => Response(data: {'access_token': 'abc', 'refresh_token': 'xyz'}, statusCode: 200, requestOptions: RequestOptions(path: '')),
    // );
    
    final container = ProviderContainer();
    final authNotifier = container.read(authProvider.notifier);
    
    // Trigger login
    await authNotifier.login('test@test.com', 'password123');
    
    // Verify state
    expect(container.read(authProvider).value, true);
  });
}
